[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="IRC_NICK"
    PrefixMessagesWithNick=true
    ShowJoinPart=true
    RemoteNickFormat="<{NICK}> "

[mattermost]
    [mattermost.work]   
    useAPI=true
    Server="MM_SERVER_NAME"
    Team="MM_TEAM_NAME"
    Login="MM_LOGIN"
    Password="MM_PASS"
    PrefixMessagesWithNick=true
    ShowJoinPart=false
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true
    [[gateway.in]]
    account="irc.freenode"
    channel="IRC_CHANNEL_NAME"

    [[gateway.out]]
    account="irc.freenode"
    channel="IRC_CHANNEL_NAME"

    [[gateway.in]]
    account="mattermost.work"
    channel="MM_CHANNEL_NAME"

    [[gateway.out]]
    account="mattermost.work"
    channel="MM_CHANNEL_NAME"
